### PR TITLE
Cross build to scala 3.0.0-RC3

### PR DESCRIPTION
**Pull request by bchazalet**
TDLR; compiling squeryl under scala 3.0.0-M3 is almost there but not quite.

This PR does a number of things to allow for the code to be compiled under scala 3.0.0-M3:
- fix indentation where the scala 3 complained and could not figure out what was happening
- in scala 3, types of implicit values and result types of implicit methods must be explicitly declared. There are a lot of this in this PR
- change use of `reflect.Manifest` to `reflect.ClassTag`. The former is not available anymore in scala 3, but the latter does the job instead
- use a version of scalatest that is compiled against scala 3.0.0-M3
- use a version of the xml modules that is compiled against scala 3.0.0-M3, but only for the scala 3 compilation

Now there are a few things for which this PR falls short:
- type inference and implicit resolution have changed in scala 3 and for squeryl this means that the query dsl is not able to infer the right types in some places (mostly in `compute` and `avg`, `sum`, `min`, `max` functions). However, I believe that with a better understanding of how they work in scala 3, we should be able to improve the current situation and get very close to what we have in scala 2.
- two tests are still failing to compile because of ambiguous implicit arguments (related to the previous point). I am going to try to get to a place where they at least compile
- the `optionTypeFromScalaSig(member: Member): Option[Class[_]]` function uses reflection to determine the generic -and erased- type inside the Option, using some helper code from json4s-scalap. However this is not going to work in scala 3 and I have no idea how it can be replaced. This is the biggest blocker I see towards scala 3: __if anyone can point me in the right direction, I can try to work on a solution (a macro?). Even explaining what this function does and why it's needed would be very much appreciated.__ I've asked the json4s-scalap people about scala 3 support [here](https://github.com/json4s/json4s/issues/743) and it doesn't sound trivial.

_____
This PR got quite big: if needed I could split the changes that prepares for scala 3 but don't require it (indentation fixes, Manifest -> ClassTag, explicit types for implicit values) into a first PR that could be merged without much risk.

### CODE REVIEW

**Comment by pbrant** [comment]
Wow! This is really, really awesome. We'll be using Squeryl the foreseeable future and this is something I was not looking forward to having to do.

Regarding optionTypeFromScalaSig, for the most part Squeryl uses Java reflection to resolve types internally, but that doesn't work for Option fields in the face of type erasure. scalap is used to recover the Scala signature in that case. It could most definitely be rewritten to use either Scala reflection or a macro. 

We're using a fork that includes hacked in support for Scalaz tagged types, but I didn't want to introduce that dependency in this repo, even indirectly:

That code is here:

https://github.com/ccap/Squeryl/commit/1ec530e1b13268e10ae1167ed4813d25824de5ed

I'm as of yet totally unfamiliar with reflection in Scala 3, but hopefully the above wouldn't be too far off from what you need (less the Scalaz parts).

**Comment by bchazalet** [comment]
thanks @pbrant for the encouragements, it's much appreciated!

I'll think I am going to have to study what is available in scala 3 in terms of reflection: it looks like your fork uses `universe` which won't be there. I also stumble on this yesterday night which might provide useful machinery: https://github.com/gzoller/scala-reflection

**Comment by bchazalet** [comment]
I finally got this working against scala 3.0.0-RC2.

The `optionTypeFromScalaSig` method that uses scala 2 reflection to figure out the contained type of `Option` columns just cannot be ported to scala 3. Instead, I've written a macro that extracts that information at compile time and passes it down the stack of methods until it's needed. 

As mentioned in my previous comment, type inference doesn't work everywhere like it used to so more investigation is required there. Also, after I was successfully able to compile, I've noticed that the infix use of methods like `select` isn't quite working anymore. The compiler doesn't complain but what happens is that the `select` isn't 'attached' to the rest of the query and the `where` clause is usually dropped. This is pretty bad because it does so silently and is only caught up by the tests. The [rules around infix operators](https://dotty.epfl.ch/docs/reference/changed-features/operators.html) have changed and I'm not optimistic this can be made to work so this needs more investigation too. Worse comes to worse, we'll have to prefix `select`, `on`, `compute`, etc with a `.` at the call site which I think is ok.

Note that the github action fails compiling against scala 3 with a `dotty.tools.dotc.core.Denotations$StaleSymbol: stale symbol;` which happens indeed on one of my computer but not the other. Not sure what this is about, but I can confirm I can compile and run the tests on one of them.

**Comment by bchazalet** [comment]
first green checks! Even though I manually edited some of the tests, this is progress.

**Comment by pbrant** [comment]
Awesome! Very, very cool.

**Comment by bchazalet** [comment]
closing this in favour of https://github.com/squeryl/squeryl/pull/321

**Pull request closed without merging**
